### ISSUE TITLE
In forms.svyNumberPopupFilter it say onActionToggleSmallerThen but the operator is scopes.svyPopupFilter.OPERATOR.SMALLER_EQUAL

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#30] opened 2020-08-04 07:00 UTC
Hi,
In forms.svyNumberPopupFilter  two function that are not coherent.

```

/**
 * @param {JSEvent} event
 *
 * @protected
 *
 * @properties={typeid:24,uuid:"5742086A-6023-4D71-807C-5764C6984519"}
 */
function onActionToggleBiggerThen(event) {
	toggleOperator(scopes.svyPopupFilter.OPERATOR.GREATER_EQUAL);
}

/**
 * @param {JSEvent} event
 *
 * @protected
 *
 * @properties={typeid:24,uuid:"2B9B6314-E227-482B-BB1D-E47D89D93AF6"}
 */
function onActionToggleSmallerThen(event) {
	toggleOperator(scopes.svyPopupFilter.OPERATOR.SMALLER_EQUAL);
}
```
My suggestion is correct them an increase in two new function for that features.

Un Saludo

Juan Ramírez

**Comment by paronne** [comment] 2020-08-04 07:06
Hi Juan,

this issue is a duplicate of [#20](https://github.com/Servoy/svyPopupFilter/issues/20) which has been already resolved. Will be available with the next release.

Regards,
Paolo

**Closed as completed by paronne** 2020-08-04 07:06 UTC
