### ISSUE TITLE
Can I add at toolbarFilter more Popup elements? 

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#13] opened 2020-03-25 09:13 UTC
Hi, 
studying the "Free Search Custom Configuration" work well with the "addSearchProvider".
`var simpleSearch = toolbarFilter.getSimpleSearch();
	// add a search provider not available in grid
	simpleSearch.addSearchProvider("peso", "peso", false);`

My question is:
Can I include at  toolbarFilter more Popup elements?
![Image 2](https://user-images.githubusercontent.com/26114868/77519821-16733000-6e78-11ea-8e33-e6954525028c.png)

Un Saludo

Juan Ramírez

**Comment by paronne** [comment] 2020-03-25 11:01
Hi Juan, i believe this feature request is a duplicate of https://github.com/Servoy/svyPopupFilter/issues/4

Currently you can achieve it by adding "hidden" columns in the grid to be used just to populate the filters. For these columns you would set visible = false and enableToolPanel=false so the user won't be able to show them at all.

Adding filters via scripting is still a valid use case, more intuitive and more performing; is part of our road map

**Comment by paronne** [comment] 2020-12-16 12:12
Implemented for version 2.0.0

**Closed as completed by paronne** 2020-12-16 12:12 UTC
