### ISSUE TITLE
function newInstance(filterObj) in Forms.AbstractPopup create a formName with UUID than has '-'

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPopupFilter#28] opened 2020-07-31 05:38 UTC
Hi.
the function newInstance(filterObj) in Forms.AbstractLookup create a form that show a warning in the log of servoyServer.

WARN com.servoy.j2db.util.Debug - The name 'D016AE88-5BF5-48B9-84BA-CBF239DA08EC' is not a valid indentifier for a component/form, please change this (avoid '-' or other invalid chars, replace those with '_', also can't start with a number)

Un Saludo

Juan Ramírez

**Comment by paronne** [comment] 2020-07-31 06:57
This issue is a duplicate of [SVYX-29](https://support.servoy.com/browse/SVYX-29).
Is already resolved and will be available with next release

**Closed as completed by paronne** 2020-07-31 06:57 UTC
